name: Documentation

on:
  push:
    # sync/**: merge commits created while syncing with the upstream fork can conflict in
    # ways that don't trigger CI on a pull_request event alone.
    branches: [ "2/edge", "sync/**" ]
  pull_request:

jobs:
  docs-checks:
    uses: canonical/operator-workflows/.github/workflows/docs.yaml@main
    secrets: inherit
    with:
      vale-files: '["README.md","CONTRIBUTING.md"]'
