name: Update Terraform documentation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-docs:
    name: Update Terraform documentation
    uses: canonical/operator-workflows/.github/workflows/generate_terraform_docs.yaml@main
    secrets: inherit
    with:
      terraform-directory: terraform/charm,terraform/charm/large_deployment,terraform/charm/simple_deployment,terraform/product,terraform/product/large_deployment,terraform/product/simple_deployment
