name: Update Terraform documentation

on:
  pull_request:
  push:
    branches:
      - 2/edge
      # sync/**: merge commits created while syncing with the upstream fork can conflict in
      # ways that don't trigger CI on a pull_request event alone.
      - 'sync/**'

jobs:
  terraform-docs:
    name: Update Terraform documentation
    uses: canonical/operator-workflows/.github/workflows/generate_terraform_docs.yaml@main
    secrets: inherit
    with:
      terraform-directory: terraform/charm,terraform/charm/large_deployment,terraform/charm/simple_deployment,terraform/product,terraform/product/large_deployment,terraform/product/simple_deployment
