name: Test prometheus rules

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  promtool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # prometheus snap includes promtool
      - name: Install prometheus snap
        run: sudo snap install prometheus

      - name: Check validity of prometheus alert rules
        run: |
          promtool check rules src/alert_rules/prometheus/*.yaml

      - name: Run unit tests for prometheus alert rules
        run: |
          promtool test rules tests/unit/test_alert_rules/*.yaml
